version: "3.7"

x-common: &common
  build:
    context: .
  env_file: .env
  environment: &common-env
    LOCUST_OPTS: "--web-host=0.0.0.0"

services:
  locust-master:
    <<: *common
    ports:
      - 8089:8089
    environment:
      <<: *common-env
      LOCUST_MODE: master

  locust-slave:
    <<: *common
    environment:
      <<: *common-env
      LOCUST_MODE: slave
      LOCUST_MASTER_HOST: locust-master
      LOCUST_MASTER_PORT: 5557

  redis:
    image: redis:5.0.8-alpine
