apiVersion: apps/v1
kind: Deployment
metadata:
  name: locust-slave
  labels:
    app: locust-slave
spec:
  replicas: 10
  selector:
    matchLabels:
      app: locust-slave
  template:
    metadata:
      labels:
        app: locust-slave
    spec:
      containers:
        - name: locust-slave
          image: [IMAGE]
          env:
            - name: LOCUST_MODE
              value: slave
            - name: LOCUST_OPTS
              value: --web-host=0.0.0.0
            - name: TARGET_URL
              value: [TARGET_URL]
            - name: LOCUST_MASTER_HOST
              value: locust-master
            - name: LOCUST_MASTER_PORT
              value: "5557"
