---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: master
  labels:
    app: master
spec:
  replicas: 1
  selector:
    matchLabels:
      app: master
  template:
    metadata:
      labels:
        app: master
    spec:
      containers:
        - name: master
          image: [IMAGE]
          imagePullPolicy: IfNotPresent
          env:
            - name: LOCUST_MODE
              value: master
            - name: LOCUST_OPTS
              value: --web-host=0.0.0.0
            - name: TARGET_URL
              value: [TARGET_URL]
            - name: LOCUSTFILE_PATH
              value: /locustfile.py
            - name: REDIS_HOST
              value: redis-svc
          ports:
            - name: master-web
              containerPort: 8089
              protocol: TCP
            - name: master-p1
              containerPort: 5557
              protocol: TCP
            - name: master-p2
              containerPort: 5558
              protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: slave
  labels:
    app: slave
spec:
  replicas: 1
  selector:
    matchLabels:
      app: slave
  template:
    metadata:
      labels:
        app: slave
    spec:
      containers:
        - name: slave
          image: [IMAGE]
          imagePullPolicy: IfNotPresent
          env:
            - name: LOCUST_MODE
              value: slave
            - name: LOCUST_OPTS
              value: --web-host=0.0.0.0
            - name: TARGET_URL
              value: [TARGET_URL]
            - name: LOCUST_MASTER_HOST
              value: locust-svc
            - name: LOCUST_MASTER_PORT
              value: "5557"
            - name: LOCUSTFILE_PATH
              value: /locustfile.py
            - name: REDIS_HOST
              value: redis-svc

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  labels:
    app: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:5.0.8-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - name: redis
              containerPort: 6379
              protocol: TCP

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: locust-svc
  name: locust-svc
spec:
  type: ClusterIP
  selector:
    app: master
  ports:
    - port: 8089
      targetPort: master-web
      protocol: TCP
      name: master-web
    - port: 5557
      targetPort: master-p1
      protocol: TCP
      name: master-p1
    - port: 5558
      targetPort: master-p2
      protocol: TCP
      name: master-p2

---

apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis-svc
  name: redis-svc
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
